### ISSUE TITLE
Expanded TreeView Item will not close correctly

### ISSUE THREAD

**Issue by WakanaYuki** [BAndysc/Classic.Avalonia#1]
First off I want to thank you so much for releasing this awesome project! I love the look and feel of this theme a lot and will fit nicely with my themed xfce install!

I have noticed that in the Classic.Demo after a TreeView item is expanded to show it's children it is not closed again correctly.

How to reproduce:
- Expand a TreeView item with children
- Close the TreeView item with children

After closing it again the space where the child of the item was displayed is still empty. I think the intended behaviour was for the item to close and the space to be fille with the items below it again.

Screenshots:
![image](https://github.com/user-attachments/assets/f658c5b7-edd4-4a02-82ce-b293f9e81f61)
![image](https://github.com/user-attachments/assets/4f41f4bf-27d1-4931-91fd-252c8d4f3b72)

**Comment by BAndysc** [comment]
Hi, thanks for your kind words, I did not notice that before, fixed!
