### ISSUE TITLE
Inconsistent text offsets on mousedown for different buttons

### ISSUE THREAD

**Issue by hacklex** [BAndysc/Classic.Avalonia#10]
Inconsistent text offsets on mousedown for different buttons.

For example, in font dialog sample:

https://github.com/user-attachments/assets/033f0dd7-ae4d-4b38-9394-09bec3d61521

One button moves its contents by (dx,dy)=(0, +1), while the other does so by (+1; +1)

**Comment by BAndysc** [comment]
I am afraid this is again font related issue, as described in https://github.com/BAndysc/Classic.Avalonia/issues/11 there is no good way to solve this. I am gonna close this issue for now and keep the other one opened.

**Comment by hacklex** [comment]
Yes, Avalonia has problems vertically centering textblocks.

However, the problem sometimes arises with buttons containing no text at all.

For example, close button of the Toolbox in VB6 sample app offsets the x image by (0, 1), while the buttons representing the controls in the toolbox are all offset by (1, 0).
