### ISSUE TITLE
Consider expose the "Hide Win11 corner" function as AttachedProperty

### ISSUE THREAD

**Issue by rabbitism** [BAndysc/Classic.Avalonia#4]
So that user can utilize in any kind of window. It is possible to subscribe to the change of IsExtendedIntoWindowDecorationsProperty and apply the coercion. I have tested it locally and it works well. 
(And I can open a PR if needed. )

**Comment by BAndysc** [comment]
I was thinking about an attached property, but I am afraid observing `IsExtendedIntoWindowDecorationsProperty` is not enough.

Avalonia sets `DWMWA_WINDOW_CORNER_PREFERENCE` in `ExtendClientArea()`. `ExtendClientArea` is called when `IsExtendedIntoWindowDecorationsProperty` changes, but also in few different cases (ShowWindow, WM_SIZE message, few different cases). So I think there is high risk our call to `no rounded corners` could be replaced by Avalonia's call breaking the classic style.

I think it is better to just implement it on the Avalonia side: https://github.com/AvaloniaUI/Avalonia/issues/17294

**Comment by BAndysc** [comment]
Hmm, how do you use coercion with DirectProperty? I thought only StyledProperty supports it? Tho I think that's still a hack, as coercion should not have side effects (but in this particular case it is not very problematic).

**Comment by rabbitism** [comment]
> Hmm, how do you use coercion with DirectProperty? I thought only StyledProperty supports it? Tho I think that's still a hack, as coercion should not have side effects (but in this particular case it is not very problematic).

Sorry was a bit busy these days.  Please check below commit: https://github.com/rabbitism/Classic.Avalonia/commit/032a59bddbb6725f4aa62cddae432bb7e06253da

**Comment by BAndysc** [comment]
This is not enough. This callback will only fire on an effective property value change, i.e. only once, because we don't change `IsExtendedIntoWindowDecorationsProperty`. On the other hand `ExtendClientAreaToDecorations` in Window Impl is called more often. I.e. when you minimize and restore the window. In this case the rounded borders fix will be overriden by the default behavior.

So implementing it on the Avalonia side is the only option.

**Comment by BAndysc** [comment]
Waiting for https://github.com/AvaloniaUI/Avalonia/pull/17354 to be merged
