### ISSUE TITLE
Sub-menu items use incorrect text color

### ISSUE THREAD

**Issue by Splitwirez** [BAndysc/Classic.Avalonia#5]
![sub-menu items with white text](https://github.com/user-attachments/assets/64059b5f-ea4b-4c07-9f7d-6c0c1904b399)

I suspect this occurs due to the sub-menu items inheriting the (white) foreground color of the parent menu item, as moving the cursor over to another item (NOT into the sub-menu) - which deselects the parent menu item - causes the sub-menu items to appear with the correct black color in the brief moment before the sub-menu closes.

---

...neat project btw :+1:

**Comment by Splitwirez** [comment]
> https://github.com/BAndysc/Classic.Avalonia/pull/3

lmao someone already opened a PR to fix this...my bad lol

**Comment by BAndysc** [comment]
I don't know how I missed that :D The PR is now merged, so closing the issue.

> ...neat project btw 👍

Cheers!
