### ISSUE TITLE
Color palettes per window and maybe tabs?

### ISSUE THREAD

**Issue by Shadowblitz16** [BAndysc/Classic.Avalonia#7]
Color themes similar to how roller coaster tycoon 2 had it
![image](https://github.com/user-attachments/assets/0fea0fbb-e129-4c31-98f3-29823d5a6395)

**Comment by BAndysc** [comment]
You can apply theme per window or even per control. Just set `RequestedThemeVariant="{x:Static ClassicTheme.Classic}"` on anything you want to style :)

**Comment by BAndysc** [comment]
Yes, RequestThemeVariant is used to use different theme colors, including custom palettes.
Take a look at this file: https://github.com/BAndysc/Classic.Avalonia/blob/master/src/Classic.Avalonia.Theme/Colors/Plum.axaml which contains palette and then this file: https://github.com/BAndysc/Classic.Avalonia/blob/master/src/Classic.Avalonia.Theme/Colors/Colors.axaml#L48 to include the correct file depending on the chosen ThemeVariant. This way you can create custom palettes and assign them to chosen components

**Comment by Shadowblitz16** [comment]
thankyou
