### ISSUE TITLE
Font settings

### ISSUE THREAD

**Issue by cprkv** [BAndysc/Classic.Avalonia#9]
Hello. I like classic theme. But I have one problem - there is no option on how to change font from aliased to **anti-aliased**. I want same theme but with modern font features, and do not know how to change it.

**Comment by cprkv** [comment]
I've managed to get it via adding Classic.Avalonia libraries to my project with source code, and replace all occurrences to `RenderOptions.TextRenderingMode="Antialias"`. But this setup is a little to much I think. And if library will be updated I will not get updates. Some better solution needed...

**Comment by BAndysc** [comment]
Good point, just published a new `11.2.0.7` version, now you can set FontAliasing on the ClassicTheme to configure it to your needs, i.e.:
```
<classic:ClassicTheme FontAliasing="False" />
```
